### PR TITLE
feat: add iPad Support

### LINKED ISSUE #21: iPadOS App
Love the app! Is an iPad version planned as well? (same question for ShelfPlayer)

### PR DESCRIPTION
**Pull request by gnattu**
This PR added iPad support and the required layout adjustments for it. Additionally, it fixed the problem where some buttons could only be tapped on the text, which is particularly annoying on larger screens like the iPad.

Furthermore, this PR addressed the performance issue on large libraries with more than 10K albums by implementing lazy loading for albums and tracks instead of loading all of them at once.

Some concerns for the current implementation include:

- The spotlight integration still requires loading all tracks at once. Is there a better way to handle this?
- I noticed you are using Label instead of Button in some places. Is there a specific reason for this choice?

Fixes #21

### CODE REVIEW

**Comment by rasmuslos** [comment]
Could you split this PR into two? One for the lazy loading (and this hit target fix, it is great!) and one for the iPad support would be great! While I am all for lazy loading I do have some issues with the iPad version.

- I think the spotlight integration can be improved, it should be possible to run the import in multiple runs.
- What do you mean by using labels instead of buttons? Can you give an example?

Some things I noticed with the iPad version:

- The album buttons are to far down next to the album cover
- The spacing for albums is not all over the place on different screen sizes. Ideally the padding is the same as the gap between the albums:

Simulator Screenshot - iPhone 15 Pro Max - 2024-04-05 at 21 31 22
Simulator Screenshot - iPhone 15 Pro Max - 2024-04-05 at 21 25 03

- Some links behave weird:

Simulator Screenshot - iPhone 15 Pro Max - 2024-04-05 at 21 25 52

- The size and especially the animation of the now playing view behave rather strange

Simulator Screenshot - iPad Pro (12 9-inch) (6th generation) (16GB) - 2024-04-05 at 21 27 19
Simulator Screenshot - iPad Pro (12 9-inch) (6th generation) (16GB) - 2024-04-05 at 21 27 14

**Comment by rasmuslos** [comment]
Also albums are way to big on small devices

Simulator Screenshot - iPhone SE (3rd generation) - 2024-04-05 at 21 23 52

**Comment by gnattu** [comment]
> The size and especially the animation of the now playing view behave rather strange

I already find the root cause of this thing but I need to come up with a more proper fix later. This is a very very interesting behavior when you attempted to use `UIScreen` to set bounds and then things happened. The `UIScreen` bounds is not safe to use on larger screens as they will return mysterious values and that value will not make your view fit to full screen.

What's more, on iPad there will be chances that the view is resized, so it will be smaller than the screen size. I need to find a way that not relies on the UIScreen to get bounds on iPad.

**Comment by rasmuslos** [comment]
> Like this in AlbumsView+Header:

This is because the whole layout has to be contained inside a `List` (otherwise swipe actions do not work and you cannot really set the size of a list without it breaking your whole layout). Some apple employee decided that it would be funny if buttons contained in the same list row should have stupid it targets so if you clicked on the shuffle button the other one might trigger.

> Can you be more specific? If you are taking about the play/shuffle button on the iPad layout, then yes it is far down and needs to be fixed, but I'm not quite sure.

Yes

> I agree the spacing can be improved, but actually it is OK as even Apple themselves does not guarantee the equal-width padding on iPad:

I have to use the iPadOS app for a while to get a feel for it but it should be consistent on iOS

**Pull request closed without merging**
